In [1]:
from bs4 import BeautifulSoup

html_doc = """  
<html><head><title>Happygrammer's story</title></head>
<body>
<p class="title"><b>Happygrammer's story</b></p>
<p class="story">Hello, Happygrammer World
<a href="http://happygrammer.com/hello" class="sister" id="link1">Elsie</a>,
<a href="http://example.com/happy" class="sister" id="link2">Lacie</a>
"""

In [2]:
def removeHtmlTags(text):
    soup = BeautifulSoup(text, "html.parser")
    txt = soup.get_text(separator=" ")
    return txt

In [3]:
removeHtmlTags(html_doc)

"\n Happygrammer's story \n \n Happygrammer's story \n Hello, Happygrammer World\n Elsie ,\n Lacie \n"

In [4]:
import re

data = "<p>초등학교 입학을 축하합니다.~~~^^;<br/></p>"
soup = BeautifulSoup(data, "html5lib")
remove_tag = soup.get_text()
result_text = re.sub('[-=+,#/\?:^$.@*\"※~&%ㆍ!』\\‘|\(\)\[\]\<\>`\'…》;]', ''
              , remove_tag)
print(result_text)

초등학교 입학을 축하합니다


In [5]:
p=re.compile("[0-9]+")
p.sub("","서울부동산 가격이 올해 들어 평균 30% 상승했습니다.")

'서울부동산 가격이 올해 들어 평균 % 상승했습니다.'

In [6]:
p=re.compile('[^ㄱ-ㅣ가-힣A-Za-z]')
p.sub(" ","▲▰ ◆▼○▽△ ▭ @#$%^$%$this is spam~!!@#$%^^*")

'                   this is spam          '

In [7]:
text="I was wondering if anyone out there could enlighten me on this car"
shortword=re.compile(r'\W*\b\w{1,2}\b')
print(shortword.sub('',text))

 was wondering anyone out there could enlighten this car


In [8]:
sentence = 'I visited US from UK on 22-10-18'
normalized_sentence = sentence.replace("US", "United State").replace("UK", "United Kingdom").replace("-18","-2018")
print(normalized_sentence)

I visited United State from United Kingdom on 22-10-2018


In [11]:
from autocorrect import Speller
spell = Speller()
sentence = "Natral Language Procesing deals with the art of extracting insightes from Natural Languages."

spell(sentence)

'Natural Language Processing deals with the art of extracting insights from Natural Languages.'

In [10]:
pip install autocorrect

  Created wheel for autocorrect: filename=autocorrect-2.5.0-py3-none-any.whl size=621863 sha256=16f7649b731f2df1ef3b147d97e88ccfe43166ba756025d2531f50d78f1adef6
  Stored in directory: c:\users\kdg\appdata\local\pip\cache\wheels\3d\8e\bd\f6fd900a056a031bf710a00bca338d86f43b83f0c25ab5242f
Successfully built autocorrect
Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [12]:
s="Hello World"
print(s.lower(),s.upper())

hello world HELLO WORLD


In [13]:
from nltk.tokenize import word_tokenize 
print(word_tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))



['Do', "n't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr.', 'Jone', "'s", 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [14]:
from nltk.tokenize import WordPunctTokenizer 
print(WordPunctTokenizer().tokenize("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))



['Don', "'", 't', 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', ',', 'Mr', '.', 'Jone', "'", 's', 'Orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop', '.']


In [16]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence 
print(text_to_word_sequence("Don't be fooled by the dark sounding name, Mr. Jone's Orphanage is as cheery as cheery goes for a pastry shop."))



["don't", 'be', 'fooled', 'by', 'the', 'dark', 'sounding', 'name', 'mr', "jone's", 'orphanage', 'is', 'as', 'cheery', 'as', 'cheery', 'goes', 'for', 'a', 'pastry', 'shop']


In [17]:
from nltk.tokenize import TreebankWordTokenizer 
tokenizer=TreebankWordTokenizer() 
text="Starting a home-based restaurant may be an ideal. it doesn't have a food chain or restaurant of their own." 
print(tokenizer.tokenize(text))



['Starting', 'a', 'home-based', 'restaurant', 'may', 'be', 'an', 'ideal.', 'it', 'does', "n't", 'have', 'a', 'food', 'chain', 'or', 'restaurant', 'of', 'their', 'own', '.']


In [18]:
from nltk.tokenize import sent_tokenize 
text="I am actively looking for Ph.D. students, and you are a Ph.D student." 
print(sent_tokenize(text))



['I am actively looking for Ph.D. students, and you are a Ph.D student.']


In [21]:
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize 
import nltk
print("영어 stopword 개수",len(nltk.corpus.stopwords.words('english')))
print(nltk.corpus.stopwords.words('english')[:20])

example = "Family is not an important thing. It's everything."
stop_words = set(stopwords.words('english')) 

word_tokens = word_tokenize(example)

result = []
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 

print(word_tokens) 
print(result) 

영어 stopword 개수 179
['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his']
['Family', 'is', 'not', 'an', 'important', 'thing', '.', 'It', "'s", 'everything', '.']
['Family', 'important', 'thing', '.', 'It', "'s", 'everything', '.']


In [22]:
from nltk.stem import PorterStemmer
s=PorterStemmer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([s.stem(w) for w in words])

['polici', 'do', 'organ', 'have', 'go', 'love', 'live', 'fli', 'die', 'watch', 'ha', 'start']


In [23]:
from nltk.stem import LancasterStemmer
l=LancasterStemmer()
words=['policy', 'doing', 'organization', 'have', 'going', 'love', 'lives', 'fly', 'dies', 'watched', 'has', 'starting']
print([l.stem(w) for w in words])

['policy', 'doing', 'org', 'hav', 'going', 'lov', 'liv', 'fly', 'die', 'watch', 'has', 'start']


In [24]:
from nltk.stem import WordNetLemmatizer

lemma = WordNetLemmatizer()
print(lemma.lemmatize('amusing'),lemma.lemmatize('amuses'),lemma.lemmatize('amused'))
print(lemma.lemmatize('happier'),lemma.lemmatize('happiest'))
print(lemma.lemmatize('fancier'),lemma.lemmatize('fanciest'))

amusing amuses amused
happier happiest
fancier fanciest


In [25]:
import konlpy
from konlpy.tag import Okt  
okt=Okt()  
print(okt.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['열심히', '코딩', '한', '당신', ',', '연휴', '에는', '여행', '을', '가봐요']


In [26]:
from konlpy.tag import Kkma  
kkma=Kkma()  
print(kkma.morphs("열심히 코딩한 당신, 연휴에는 여행을 가봐요"))

['열심히', '코딩', '하', 'ㄴ', '당신', ',', '연휴', '에', '는', '여행', '을', '가보', '아요']


In [28]:
pip install kss

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not install packages due to an OSError: [WinError 5] 액세스가 거부되었습니다: 'C:\\ProgramData\\Anaconda3\\Lib\\site-packages\\tests\\__init__.py'
Consider using the `--user` option or check the permissions.

You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [29]:
import kss

text='딥 러닝 자연어 처리가 재미있기는 합니다. 그런데 문제는 영어보다 한국어로 할 때 너무 어려워요. 농담아니에요. 이제 해보면 알걸요?'
print(kss.split_sentences(text))

['딥 러닝 자연어 처리가 재미있기는 합니다.', '그런데 문제는 영어보다 한국어로 할 때 너무 어려워요.', '농담아니에요.', '이제 해보면 알걸요?']


In [30]:


example = "고기를 아무렇게나 구우려고 하면 안 돼. 고기라고 다 같은 게 아니거든. 예컨대 삼겹살을 구울 때는 중요한 게 있지."
stop_words = "아무거나 아무렇게나 어찌하든지 같다 비슷하다 예컨대 이럴정도로 하면 아니거든"
# 위의 불용어는 명사가 아닌 단어 중에서 저자가 임의로 선정한 것으로 실제 의미있는 선정 기준이 아님
stop_words=stop_words.split(' ')
word_tokens = word_tokenize(example)

result = [] 
for w in word_tokens: 
    if w not in stop_words: 
        result.append(w) 
# 위의 4줄은 아래의 한 줄로 대체 가능
# result=[word for word in word_tokens if not word in stop_words]

print(word_tokens) 
print(result)

['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '구우려고', '안', '돼', '.', '고기라고', '다', '같은', '게', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']


In [31]:
korean_stopwords_path='./stopword.txt'
with open(korean_stopwords_path,encoding='utf-8') as f:
    stopwords=f.readlines()
stopwords=[x.strip() for x in stopwords]
result=[word for word in word_tokens if not word in stopwords]

print(word_tokens)
print(result)

['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '예컨대', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']
['고기를', '아무렇게나', '구우려고', '하면', '안', '돼', '.', '고기라고', '다', '같은', '게', '아니거든', '.', '삼겹살을', '구울', '때는', '중요한', '게', '있지', '.']


In [34]:
from pykospacing import spacing
sent = '김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다.'
kospacing_sent=spacing(sent)
print(kospacing_sent)

ModuleNotFoundError: No module named 'pykospacing'

In [36]:
from scipy import sparse
import numpy as np
dense2 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])

# 0 이 아닌 데이터 추출
data2 = np.array([1, 5, 1, 4, 3, 2, 5, 6, 3, 2, 7, 8, 1])

# 행 위치와 열 위치를 각각 array로 생성 
row_pos = np.array([0, 0, 1, 1, 1, 1, 1, 2, 2, 3, 4, 4, 5])
col_pos = np.array([2, 5, 0, 1, 3, 4, 5, 1, 3, 0, 3, 5, 0])

# COO 형식으로 변환 
sparse_coo = sparse.coo_matrix((data2, (row_pos,col_pos)))

# 행 위치 배열의 고유한 값들의 시작 위치 인덱스를 배열로 생성
row_pos_ind = np.array([0, 2, 7, 9, 10, 12, 13])

# CSR 형식으로 변환 
sparse_csr = sparse.csr_matrix((data2, col_pos, row_pos_ind))

print('COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_coo.toarray())
print('CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인')
print(sparse_csr.toarray())

COO 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
CSR 변환된 데이터가 제대로 되었는지 다시 Dense로 출력 확인
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]


In [43]:
from nltk.stem.snowball import SnowballStemmer
#
from sklearn.feature_extraction.text import CountVectorizer

x_data = np.array([
  'me free lottery',
  'free get free you',
  'you free scholarship',
  'free to contact me',
  'you won award',
  'you ticket lottery',
  'you ticket lottery',
  'you ticket lottery',
  'you ticket lottery',
  'you ticket lottery'
])
for i, document in enumerate(x_data):
    clean_words = []
    for word in nltk.tokenize.word_tokenize(document):
        word = word.lower()
        stemmer = nltk.stem.snowball.SnowballStemmer('english')
        word = stemmer.stem(word) #어간 추출
        clean_words.append(word)
    print(clean_words) #['stale', 'uninspir']
    document = ' '.join(clean_words)
    print(document) #stale uninspir
    x_data[i] = document

['me', 'free', 'lotteri']
me free lotteri
['free', 'get', 'free', 'you']
free get free you
['you', 'free', 'scholarship']
you free scholarship
['free', 'to', 'contact', 'me']
free to contact me
['you', 'won', 'award']
you won award
['you', 'ticket', 'lotteri']
you ticket lotteri
['you', 'ticket', 'lotteri']
you ticket lotteri
['you', 'ticket', 'lotteri']
you ticket lotteri
['you', 'ticket', 'lotteri']
you ticket lotteri
['you', 'ticket', 'lotteri']
you ticket lotteri


In [39]:
print(x_data)

['me free lotteri' 'free get free you' 'you free scholarship'
 'free to contact me' 'you won award' 'you ticket lotteri'
 'you ticket lotteri' 'you ticket lotteri' 'you ticket lotteri'
 'you ticket lotteri']


In [40]:
vectorizer = CountVectorizer()
vectorizer.fit(x_data)
print(vectorizer.get_feature_names())
print(vectorizer.vocabulary_)

['award', 'contact', 'free', 'get', 'lotteri', 'me', 'scholarship', 'ticket', 'to', 'won', 'you']
{'me': 5, 'free': 2, 'lotteri': 4, 'get': 3, 'you': 10, 'scholarship': 6, 'to': 8, 'contact': 1, 'won': 9, 'award': 0, 'ticket': 7}


In [44]:
x_data = vectorizer.transform(x_data)
print(x_data.shape) 
print(x_data.toarray())

(10, 11)
[[0 0 1 0 1 1 0 0 0 0 0]
 [0 0 2 1 0 0 0 0 0 0 1]
 [0 0 1 0 0 0 1 0 0 0 1]
 [0 1 1 0 0 1 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 1]
 [0 0 0 0 1 0 0 1 0 0 1]]


In [57]:
import pandas as pd
import urllib.request
from konlpy.tag import Okt
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_train.txt", filename="ratings_train.txt")
urllib.request.urlretrieve("https://raw.githubusercontent.com/e9t/nsmc/master/ratings_test.txt", filename="ratings_test.txt")
train_data = pd.read_table('ratings_train.txt')
test_data = pd.read_table('ratings_test.txt')

In [47]:
train_data.head()

id                                           document  label
0   9976970                                아 더빙.. 진짜 짜증나네요 목소리      0
1   3819312                  흠...포스터보고 초딩영화줄....오버연기조차 가볍지 않구나      1
2  10265843                                  너무재밓었다그래서보는것을추천한다      0
3   9045019                      교도소 이야기구먼 ..솔직히 재미는 없다..평점 조정      0
4   6483659  사이몬페그의 익살스런 연기가 돋보였던 영화!스파이더맨에서 늙어보이기만 했던 커스틴 ...      1

In [49]:
def tokenize(doc):
    return ['/'.join(t) for t in okt.pos(doc, norm=True, stem=True)]

In [50]:
tokenize(train_data.iloc[0,1])

['아/Exclamation',
 '더빙/Noun',
 '../Punctuation',
 '진짜/Noun',
 '짜증나다/Adjective',
 '목소리/Noun']

In [51]:
tokenize(train_data.iloc[2,1])

['너/Modifier',
 '무재/Noun',
 '밓었/Noun',
 '다그/Noun',
 '래서/Noun',
 '보다/Verb',
 '추천/Noun',
 '한/Josa',
 '다/Adverb']

In [59]:
train_data['document']=train_data['document'].str.replace("[^ㄱ-ㅎ ㅏ-ㅣ가-힣]","")

In [60]:
train_data['document'][:5]

0                                    아 더빙 진짜 짜증나네요 목소리
1                           흠포스터보고 초딩영화줄오버연기조차 가볍지 않구나
2                                    너무재밓었다그래서보는것을추천한다
3                            교도소 이야기구먼 솔직히 재미는 없다평점 조정
4    사이몬페그의 익살스런 연기가 돋보였던 영화스파이더맨에서 늙어보이기만 했던 커스틴 던...
Name: document, dtype: object

In [64]:
stopwords = ['의','가','이','은','들','는','좀','잘','걍','과','도','를','으로','자','에','와','한','하다']
okt = Okt()
X_train = []
for sentence in train_data['document'][0:1000]:
    temp_X=[]
    temp_X = okt.morphs(sentence, stem=True) # 토큰화
    temp_X = [word for word in temp_X if not word in stopwords] # 불용어 제거
    X_train.append(temp_X)
    

In [65]:
X_train[0:5]

[['아', '더빙', '진짜', '짜증나다', '목소리'],
 ['흠', '포스터', '보고', '초딩', '영화', '줄', '오버', '연기', '조차', '가볍다', '않다'],
 ['너', '무재', '밓었', '다그', '래서', '보다', '추천', '다'],
 ['교도소', '이야기', '구먼', '솔직하다', '재미', '없다', '평점', '조정'],
 ['사이',
  '몬페',
  '그',
  '익살스럽다',
  '연기',
  '돋보이다',
  '영화',
  '스파이더맨',
  '에서',
  '늙다',
  '보이다',
  '커스틴',
  '던스트',
  '너무나도',
  '이쁘다',
  '보이다']]

In [1]:
from gensim.models import Word2Vec
model = Word2Vec(sentences = tokenized_data, size = 100, window = 5, min_count = 5, workers = 4, sg = 0)

ModuleNotFoundError: No module named 'gensim'

In [2]:
pip install genism

Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement genism (from versions: none)
ERROR: No matching distribution found for genism
You should consider upgrading via the 'C:\ProgramData\Anaconda3\python.exe -m pip install --upgrade pip' command.


In [3]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
xys = pca.fit_transform(word_vectors_list)
xs = xys[:,0]
ys=xys[:,1]

NameError: name 'word_vectors_list' is not defined

In [ ]:
import matplotlib.pyplot as plt

def plot_2d_graph(vocabs, xs, ys):
    plt.figure(figsize=(15,10))
    plt.scatter(xs,ys,marker='o')
    for i,v in enumerate(vocabs):
        plt.annotate(v,xy=(xs[i], ys[i]))
        
plot_2d_graph(vocabs, xs,ys)

In [ ]:
model2 = TSNE(learning_rate = 10)
transformed = model2.fit_transform(word_vectors_list)

xs2 = transformed[:,0]
ys2 = transformed[:,1]

plt.figure(figsize=(20,18),dpi=200)

plt.scatter(xs2,ys2)

for i,v in enumerate(vocabs):
    plt.annotate(v, xy=(xs2[i],ys2[i]))
    
plt.show()

In [ ]:
model2=Word2Vec(X_train,vector_size=300,window=3,min_count=5,workers=1,sg=1)
word_vectors=model2.wv
vocabs=list(word_vectors.index_to_key)
word_vectrps_list=[word_vectors[v] for v in vocabs]